server:
  servlet:
    context-path: /travel-map
    
spring:
 data:
  mongodb:
   host: localhost
   port: 27017
   authentication-database: admin
   username: root
   password: example
   database: travel-map